### ISSUE TITLE
Cannot run the UML Platform examples

### ISSUE THREAD

**Issue by smishy05** [xatkit-bot-platform/xatkit-uml-platform#4]
Hi there,

I wish to run the UML platform using Xatkit. It was not present in the `platforms` directory after the initial `build`. Therefore, this is what I did:

1) In the `platforms` directory, I cloned the `xatkit-uml-platform`.

2) Then, I went into the `build/bin` directory and then, ran this command - `./start-xatkit-linux.sh ../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties`. After doing this, I get this error - 

```
Xatkit classpath:
/home/shailesh1998/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-github-platform/xatkit-github-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-chat-platform/xatkit-chat-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-slack-platform/xatkit-slack-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-log-platform/xatkit-log-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-core-platform/xatkit-core-runtime-3.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-react-platform/xatkit-react-runtime-4.0.1-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-rest-platform/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar
/home/shailesh1998/xatkit/build/bin/xatkit-nodep-jar-with-dependencies.jar
java -Dfile.encoding=UTF-8 -cp '/home/shailesh1998/xatkit/build/examples/WeatherBot/lib/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/examples/community/Twitter/CanYouTweet/lib/xatkit-twitter-runtime-1.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/examples/GitHubBots/GithubBot/lib/xatkit-github-runtime-2.1.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-github-platform/xatkit-github-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-chat-platform/xatkit-chat-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-slack-platform/xatkit-slack-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-log-platform/xatkit-log-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-core-platform/xatkit-core-runtime-3.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-react-platform/xatkit-react-runtime-4.0.1-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/plugins/platforms/xatkit-rest-platform/xatkit-rest-runtime-2.0.0-SNAPSHOT.jar:/home/shailesh1998/xatkit/build/bin/xatkit-nodep-jar-with-dependencies.jar' com.xatkit.Xatkit '../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties'
22:18:14.093 [pool-3-thread-1] INFO   - Starting Xatkit with the configuration file ../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React.properties
22:18:15.604 [pool-3-thread-1] INFO   - Loading Xatkit core libraries
22:18:15.706 [pool-3-thread-1] INFO   - 	CoreLibrary loaded
22:18:15.706 [pool-3-thread-1] INFO   - Loading Xatkit core platforms
22:18:15.941 [pool-3-thread-1] INFO   - 	GithubPlatform loaded
22:18:15.943 [pool-3-thread-1] INFO   - 	ChatPlatform loaded
22:18:15.951 [pool-3-thread-1] INFO   - 	SlackPlatform loaded
22:18:15.953 [pool-3-thread-1] INFO   - 	LogPlatform loaded
22:18:15.956 [pool-3-thread-1] INFO   - 	CorePlatform loaded
22:18:15.959 [pool-3-thread-1] INFO   - 	ReactPlatform loaded
22:18:15.966 [pool-3-thread-1] INFO   - 	RestPlatform loaded
22:18:15.967 [pool-3-thread-1] INFO   - Loading Xatkit custom libraries
22:18:15.976 [pool-3-thread-1] INFO   - 	null loaded
22:18:15.977 [pool-3-thread-1] INFO   - Loading Xatkit custom platforms
22:18:16.012 [pool-3-thread-1] ERROR  - An error occurred when starting the XatkitCore, trying to close started services
22:18:16.012 [pool-3-thread-1] ERROR  - Cannot start Xatkit, see the attached exception
com.xatkit.core.XatkitException: Cannot load the ExecutionModel at the given location: file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:187) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.core.XatkitCore.<init>(XatkitCore.java:159) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.Xatkit.main(Xatkit.java:93) ~[xatkit-nodep-jar-with-dependencies.jar:?]
Caused by: org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'executionRules' not found. (file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi, 4, 19)
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:185) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	... 2 more
Caused by: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'executionRules' not found. (file:/home/shailesh1998/xatkit/build/bin/../../platforms/xatkit-uml-platform/examples/UmlBot/UmlBot-React-Ex.xmi, 4, 19)
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.reportUnknownFeature(XMLHandler.java:2045) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleUnknownFeature(XMLHandler.java:2009) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.handleUnknownFeature(XMIHandler.java:172) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.handleFeature(XMLHandler.java:1953) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.processElement(XMLHandler.java:1048) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.processElement(XMIHandler.java:82) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:1026) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLHandler.startElement(XMLHandler.java:720) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMIHandler.startElement(XMIHandler.java:190) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1359) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[?:1.8.0_252]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327) ~[?:1.8.0_252]
	at org.eclipse.emf.ecore.xmi.impl.XMLLoadImpl.load(XMLLoadImpl.java:175) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.doLoad(XMLResourceImpl.java:261) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	at com.xatkit.util.ModelLoader.loadExecutionModel(ModelLoader.java:185) ~[xatkit-nodep-jar-with-dependencies.jar:?]
	... 2 more
```

I am not too sure if I proceeded in the right way. Please kindly help.

Eager to hear from you!

Thanks in advance.

**Comment by smishy05** [comment]
Hi,

I am really really sorry for my negligence and late reply. First of all, thanks for your reply. 

I had one doubt. I want to build models using Xatkit. The metamodel is defined. Using user input, I wish to build models. Can you please advise how I could go about using Xatkit to achieve this target? Any advice would be valuable for my research.

Eager to hear from you!
Thanks in advance!

**Comment by gdaniel** [comment]
Hi,

First of all, Xatkit isn't aimed at building models, it's a nice side effect of its modular infrastructure: Xatkit provides platforms, an abstraction mechanism that allows to do something in reaction to incoming intents. This something can be as simple as sending a textual response to the user, or as complex as building an UML model from the information extracted during the conversation.

We have played in the past with conversation-based model creation, and we have created for that purpose two platforms: the UML platform you already know, and an EMF platform that build EMF models instead of UML ones. Long story short, these platform are not supported anymore, and are out of date, as you experienced with the UML one.

I see two options to achieve what you want:
1. Update one of the two platform we have to make it work with the new version of Xatkit. I'd encourage this route if you are specifically targetting UML or EMF models.
2. Create your own platform to support model creation with the technology of your choice. You can take a look at the existing implementations to see how we did it for UML and EMF (even if they are outdated a good part of the internal logic is still the same).


As stated above the best option depends on your needs. What technology are you using to build your models?

**Comment by smishy05** [comment]
Hi, 

Thanks a lot for the reply. 

1. We are using Sirius.

2. Even, I think that the first choice is a great option. I will try to implement it! Thanks for the advice.

**Comment by gdaniel** [comment]
Hi,

If you are using Sirius I guess there is some EMF behind the scene to store your model. Updating the EMF platform is probably a good option.
Note that we have just [published an important release](https://xatkit.com/fluent-interface-building-chatbots-bots/) that should ease a bit the process: in addition to the shift from external to internal DSL, we have also put some effort in improving the integration of plain Java applications with Xatkit. Long story short, now that you can define your bot in plain Java you can also easily plug in your custom classes/workflows (e.g. creating model elements).
Note that this new version is still in beta, we need to make some adjustments, but the main idea are already there.

Let me know if you have any question!
